### ISSUE TITLE
on Windows

### ISSUE THREAD

**Issue by chakinala-kumar** [abouchama/CamelK-customerAPI#1]
Hi,
 I have started exploring camel k and found good example here. Thank you. I am using below environment to run this example
1. Windows 10 Pro
2. Minishift ( Memory 6GB, Disk space 20 GB)
3. CamelK : i have downloaded windows version of Kamel and changed the extension to .exe (Kamel.exe)
4. I was able to run the example.....even though its DEBUG mode system is not showing logger statement on console. Please let me know if i missed any thing. 
5. How can we debug this ? i did not see any logs to debug
Appreciate your response

Regards,
PChakina

**Comment by pchakina** [comment]
Thanks. i was able to fix the issue. it wa s problem with operators installation on minishift

**Comment by abouchama** [comment]
I'm glad you have found a solution for your windows installation
