### ISSUE TITLE
Spring boot with camel k on knative

### ISSUE THREAD

**Issue by chakinala-kumar** [abouchama/CamelK-customerAPI#2]
Hi,
Thanks for the example.  We would like to migrate spring boor micro service to Camel K on knative. Will it be possible to run spring boot and camel k on knative? Please suggest. 

thanks,
 pchakina

**Comment by abouchama** [comment]
Hello,

I just tried a version SB/Camelk & Knative and it works like a charm ;-)

You can give it a try with the latest version

**Comment by chakinala-kumar** [comment]
Thanks for the update. I will check and update you

**Comment by chakinala-kumar** [comment]
Hi,
Do you have any working sample  with SB using camel K on kantive. Please upload if possible.

Thanks
